### ISSUE TITLE
The CJK characters cannot be output correctly.

### ISSUE THREAD

**Issue by IveTian** [Jeremboo/animated-mesh-lines#6]
Using CJK characters will automatically output "?".

**Comment by Jeremboo** [comment]
Hi, 

It's because my converted font file only contains the basic Latin alphabet.

If you want to use CJK characters, you'll have to change this file: 
`https://github.com/Jeremboo/animated-mesh-lines/blob/master/app/utils/fontFile.js`

Try to use this website to convert your font and replace it : https://gero3.github.io/facetype.js/
